### PR TITLE
check if git repo exists before creating buffer

### PR DESCRIPTION
**Pull request by iguanacucumber**

### CODE REVIEW

**Review by isakbm — CHANGES_REQUESTED** [review]
Nice :)

I am testing it now

one thing that I notice is that we probably want to align formatting, could you make sure you use `stylua` to autoformat on save?

I use conform with the following setting for lua

```
...
formatters_by_ft = {
    lua = { 'stylua' }
}
```

The repo already contains an opinionated `.stylua.toml` config.

Thanks!

I might have some more feedback in a bit.

**Comment by iguanacucumber** [comment]
> Instead of this, why don't we do
> 
>     1. check that `git` is installed

Checking if git is installed is a bit useless, since to download this plugin you need to use git

>     2. check that git status has zero exit code indicating success and that this is a git repo :)

I tried to do that, without sucess ( i don't know alot about lua tbh )

**Comment by isakbm** [comment]
Alright, I'll paste a code snippet or two in a bit :)

**Comment by isakbm** [comment]
Took a bit of tinkering but this should do the trick, start by declaring this function

```lua
---@param cmd string
---@return boolean -- true if failure (exit code ~= 0) false otherwise (exit code == 0)
--- note that this method was sadly neede since there's some strange bug with lua's handle:close?
--- it doesn't get the exit code correctly by itself?
function check_cmd(cmd)
  local res = io.popen(cmd .. '; echo $?')
  if not res then
    return true
  end
  local last_line = '1'
  for line in res:lines() do
    last_line = line
  end
  res:close()
  return last_line ~= '0'
end
```

Then call it like so as first thing inside `draw`

```lua
  if check_cmd('git --version') then
    print('git command not found, please install it')
    return
  end

  if check_cmd('git status') then
    print('does not seem to be a valid git repo')
    return
  end
```

note that there is no need for an `else` wrapping the rest of the `draw` thanks to early return. Nice to avoid that unnecessary indentation.

**Comment by isakbm** [comment]
I think I'll just make a commit on the main branch that resolves this new issue #14 

Thanks for inspiration though, and please prefer this upstream change once I get it in :)

**Comment by iguanacucumber** [comment]
``` lua
if check_cmd('git --version > /dev/null 2>&1') then
    vim.notify('git command not found, please install it', vim.log.levels.ERROR)
    return
  end

if check_cmd('git status > /dev/null 2>&1') then
  vim.notify('does not seem to be a valid git repo', vim.log.levels.ERROR)
  return
end
```
- `git > /dev/null 2>&1` hides output to the user 
- `vim.notify('does not seem to be a valid git repo', vim.log.levels.ERROR)` send a notification through the nvim api, instead of using print statements

**Comment by isakbm** [comment]
The ` > /dev/null` pipe is a bit unnecessary, it is silent since it is already piped to the file that is used to read the results into by lua. 🤔

**Comment by iguanacucumber** [comment]
> The ` > /dev/null` pipe is a bit unnecessary, it is silent since it is already piped to the file that is used to read the results into by lua. 🤔

maybe neovim updated the line the same this function was so you didnt see it but:
20240810_23h57m22s_grim

**Comment by isakbm** [comment]
huh, I got it now too, I've never seen this before 👀 

image

**Comment by iguanacucumber** [comment]
you we're kinda right, we don't need `git > /dev/null` we just need `git 2>&1`

**Comment by isakbm** [comment]
ah yeah that makes sense I guess, I think `io.popen` only consumes the stdout, and not the stderr ?

**Comment by iguanacucumber** [comment]
yep it seems that `io.popen` [only consumes stdout](http://lua-users.org/lists/lua-l/2010-09/msg00955.html) so we have to redirect stderr to stdout with `2>&1`

**Comment by isakbm** [comment]
Thoughts ?

```lua
local log = {}

function log.info(msg)
  vim.notify(msg, vim.log.levels.INFO)
end

function log.error(msg)
  vim.notify(msg, vim.log.levels.ERROR)
end

return log
```

and 

```lua
---@param cmd string
---@return boolean -- true if failure (exit code ~= 0) false otherwise (exit code == 0)
--- note that this method was sadly neede since there's some strange bug with lua's handle:close?
--- it doesn't get the exit code correctly by itself?
function check_cmd(cmd)
  local res = io.popen(cmd .. ' 2>&1; echo $?')
  if not res then
    return true
  end
  local last_line = '1'
  for line in res:lines() do
    last_line = line
  end
  res:close()
  return last_line ~= '0'
end

---@param options I.DrawOptions
---@param args I.GitLogArgs
function M.draw(options, args)
  if check_cmd('git --version') then
    log.error('git command not found, please install it')
    return
  end

  if check_cmd('git status') then
    log.error('does not seem to be a valid git repo')
    return
  end
```

**Comment by iguanacucumber** [comment]
so if you need use this function again we can do something like this to avoid adding `2>&1` every check_cmd function call:
``` lua
  function check_cmd(cmd)
    cmd = cmd .. " 2>&1" -- redirects stderr to stdout since io.popen uses stdout
    local res = io.popen(cmd .. '; echo $?')
    if not res then
      return true
    end
    local last_line = '1'
    for line in res:lines() do
      last_line = line
    end
    res:close()
    return last_line ~= '0'
  end

  if check_cmd('git --version') then
    vim.notify('git command not found, please install it', vim.log.levels.ERROR)
    return
  end

  if check_cmd('git status') then
    vim.notify('does not seem to be a valid git repo', vim.log.levels.ERROR)
    return
  end

```

**Comment by iguanacucumber** [comment]
> Thoughts ?
> 
> ```lua
> local log = {}
> 
> function log.info(msg)
>   vim.notify(msg, vim.log.levels.INFO)
> end
> 
> function log.error(msg)
>   vim.notify(msg, vim.log.levels.ERROR)
> end
> 
> return log
> ```
> 
> and
> 
> ```lua
> ---@param cmd string
> ---@return boolean -- true if failure (exit code ~= 0) false otherwise (exit code == 0)
> --- note that this method was sadly neede since there's some strange bug with lua's handle:close?
> --- it doesn't get the exit code correctly by itself?
> function check_cmd(cmd)
>   local res = io.popen(cmd .. ' 2>&1; echo $?')
>   if not res then
>     return true
>   end
>   local last_line = '1'
>   for line in res:lines() do
>     last_line = line
>   end
>   res:close()
>   return last_line ~= '0'
> end
> 
> ---@param options I.DrawOptions
> ---@param args I.GitLogArgs
> function M.draw(options, args)
>   if check_cmd('git --version') then
>     log.error('git command not found, please install it')
>     return
>   end
> 
>   if check_cmd('git status') then
>     log.error('does not seem to be a valid git repo')
>     return
>   end
> ```
i think this is perfect

**Comment by isakbm** [comment]
seems we had a race condition :D

**Comment by iguanacucumber** [comment]
i think this should work:
``` lua
local function check_cmd(cmd)
  local result = vim.fn.system(cmd)
  local exit_code = vim.v.shell_error

  return exit_code ~= 0
end
```

**Comment by isakbm** [comment]
Truly, thank you! 🎉 

image

**Comment by isakbm** [comment]
> i think this should work:
> 
> ```lua
> local function check_cmd(cmd)
>   local result = vim.fn.system(cmd)
>   local exit_code = vim.v.shell_error
> 
>   return exit_code ~= 0
> end
> ```

Feel free to make PR for that subtle change if you want, should be much quicker to approve now! 🎉

**Comment by isakbm** [comment]
... but again we would need to check that it does not pollute some buffer with the stdout / stderr ... 😬

**Comment by isakbm** [comment]
I'll close this pull request now if you don't mind :)

**Pull request closed without merging**
